In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('salaries.csv')

In [3]:
df.head()

Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27

In [4]:
df.shape

(3, 3)

In [7]:
df['Salary']

0     50000
1    120000
2     80000
Name: Salary, dtype: int64

In [9]:
df[['Salary', 'Name']]

Salary    Name
0   50000    John
1  120000   Sally
2   80000  Alyssa

In [11]:
df['Salary'].mean()

83333.33333333333

In [12]:
df['Salary'].max()

120000

In [13]:
df['Salary'].min()

50000

In [15]:
# Condition filtering

ser_of_bool =  df['Age']  > 30

In [16]:
ser_of_bool

0     True
1     True
2    False
Name: Age, dtype: bool

In [18]:
df[ser_of_bool]

Name  Salary  Age
0   John   50000   34
1  Sally  120000   45

In [19]:
# grabbing unique values

df['Age'].unique()

array([34, 45, 27], dtype=int64)

In [20]:
# Length of unique values
df['Age'].nunique()

3

In [22]:
# Grab all columns names

df.columns

Index(['Name', 'Salary', 'Age'], dtype='object')

In [25]:
# info of the data frame (metadata)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
Name      3 non-null object
Salary    3 non-null int64
Age       3 non-null int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [26]:
# statistics metadata
df.describe()

Salary        Age
count       3.000000   3.000000
mean    83333.333333  35.333333
std     35118.845843   9.073772
min     50000.000000  27.000000
25%     65000.000000  30.500000
50%     80000.000000  34.000000
75%    100000.000000  39.500000
max    120000.000000  45.000000

In [27]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [28]:
# combing pandas and numpy
import pandas as pd
import numpy as np


In [31]:
mat = np.arange(0,50).reshape(5, 10)

In [32]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
df = pd.DataFrame(data=mat)

In [36]:
df

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49

In [37]:
mat1 = np.arange(0,10).reshape(5,2)

In [38]:
mat1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
df = pd.DataFrame(data=mat1, columns=['A', 'B'])

In [41]:
df

A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9